name: deploy-orders

on:
  push:
    branches:
      - main
    paths:
      - 'orders/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: cd orders && docker build -t triwjy/ticketing-orders .
      - run: docker push triwjy/ticketing-orders
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
      - run: doctl k cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment orders-depl
